name: tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.4'
    steps:
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: pcov

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit
